# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous integration Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install package
      run: python setup.py install
    - name: Test OpenMS converter
      run: |
        cd sdrf_pipelines
        for sdrf in testdata/*/*.sdrf.tsv
        do
          pushd $(dirname $sdrf)
            python ../../parse_sdrf.py convert-openms -s $(pwd)/../../$sdrf -t2
            diff -c experimental_design.tsv expected_experimental_design.tsv >> ../../failures.txt
            diff -c expected_openms.tsv openms.tsv >> ../../failures.txt
          popd
        done
        if [ -s failures.txt ]
        then
         exit 1
        fi
